modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="more_lens"
version="${file.jarVersion}"
displayName="MoreLens"
authors="edebe"
[[dependencies.more_lens]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.more_lens]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.more_lens]]
    modId="botania"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
